### ISSUE TITLE
$app/env has change to $app/environment in @sveltejs/kit@1.0.0-next.469

### ISSUE THREAD

**Issue by xemuj** [babichjacob/svelte-localstorage#23]
this throws an error 500
$app/env has been renamed to $app/environment
Error: $app/env has been renamed to $app/environment
    at /node_modules/@sveltejs/kit/src/runtime/app/env.js:1:20

**Comment by babichjacob** [comment]
Sorry about that! The fix has been published in version 0.4.0, available now on npm.
