### ISSUE TITLE
Indicate support for Svelte ^4

### ISSUE THREAD

**Issue by drfuzzyness** [babichjacob/svelte-localstorage#26]
Super minor issue. Currently the `package.json` indicates that Svelte version `^3.53.51` is supported and not later major versions.

https://github.com/babichjacob/svelte-localstorage/blob/cffdc0d45a3ba8274b410046c01692edaeecb179/projects/svelte-localstorage/package.json#L31-L33

I've been using `@babichjacob/svelte-localstorage` in Svelte 4 for several months without issues. Could the Svelte dependency be changed to allow version 4 as well?

```json
"svelte": "^3.53.1 || ^4.2.19"
```

Thanks!

**Comment by babichjacob** [comment]
will be closed by ee1686c8c44751782dd0c3af4d9b44075a5e9d7b once you let me know if it's working for you (published as version `1.1.2` on npm)

**Comment by drfuzzyness** [comment]
Works well, thanks!
